import React from "react";
import AnimationRevealPage from "helpers/AnimationRevealPage.js";
import { Container, ContentWithPaddingXl } from "components/misc/Layouts";
import tw from "twin.macro";
import styled from "styled-components";
import { css } from "styled-components/macro"; //eslint-disable-line
import Header from "components/headers/light.js";
import Footer from "components/footers/FiveColumnWithInputForm.js";
import { SectionHeading } from "components/misc/Headings";


import { quiz } from "./Quiz";
import ProtectingBusinessComp from "components/hero/ProtectingBusinessComp";
import ProtectingBusiness from "components/hero/ProtectingBusinessComp";

const HeadingRow = tw.div`flex`;
const Heading = tw(SectionHeading)`text-gray-900 mb-10`;
const Text = styled.div`
	${tw`text-lg  text-gray-800`}
	p {
		${tw`mt-2 leading-loose`}
	}
	h1 {
		${tw`text-3xl font-bold mt-10`}
	}
	h2 {
		${tw`text-2xl font-bold mt-8`}
	}
	h3 {
		${tw`text-xl font-bold mt-6`}
	}
	ul {
		${tw`list-disc list-inside`}
		li {
			${tw`ml-2 mb-3`}
			p {
				${tw`mt-0 inline leading-normal`}
			}
		}
	}
`;

export default ({ headingText = "Protecting your Business and Employees" }) => {
	return (
		<AnimationRevealPage>
			<ProtectingBusinessComp></ProtectingBusinessComp>
			<Container>
				<ContentWithPaddingXl>
					<HeadingRow>
						<Heading>{headingText}</Heading>
					</HeadingRow>
					<Text>
					<p>Last updated: 13th June 2023 </p>

					<h1>Things to keep a look out for </h1>

					<h1>When choosing your passphrase</h1>

					<p>
						Common things to look out for to see if someone else has accessed
						your email account:{" "}
					</p>

					<li>Unable to access your email as the password is incorrect</li>
					<li>
						There are strange emails in the sent folder You receive unexpected
						password reset notifications{" "}
					</li>
					<li>Sign ins from unusual IP addresses, devices, and/or browsers</li>
					<p>
						In certain circumstances, you may not have realised that your email
						account has been compromised until one of your contacts reports
						dubious emails from your account.
					</p>
					<p>
						A strong passphrase consists of four or more random words. Sentences
						are not ideal as passphrases since they can be more easily guessed.
						Predictable patterns like spaces between words, initial capital
						letters, and ending punctuation make sentences less secure. Opting
						for a combination of random words creates stronger and more
						unpredictable passphrases.{" "}
					</p>

					<h1>How to prevent Business email compromise</h1>
					<p>
						Implementing protective measures that are simple, cost-effective and
						immediately beneficial:
						<li>Multi-Factor Authentication</li>
						Having a multi-factor authentication increases the security on your
						email account, by having two checks in place to prove your identity
						before you can access your account. For example, you may need to
						supply an authentication code from an app as well as your password.
						This makes it more difficult for someone to access your files or
						account. Follow ACSC’s multi-factor authentication guide to learn
						how to enable multi-factor authentication. If you are unable to
						utilise multi-factor authentication, use a strong passphrase for
						your email account.
						<li>Protecting Domain Names</li>A domain name is a string of
						characters that are frequently words. It helps to identify you or
						your company to other Internet users. This is the text that follows
						the "@" symbol in an email address. If your domain name expires, it
						will be offered for purchase to anyone. A criminal may buy your old
						domain name and use it to impersonate you or your company by
						creating an email address and contacting your customers. Customers
						or contacts may recognise your domain name and believe you are still
						using that email account. Unbeknownst to them, they are
						communicating with a cyber-criminal. Remember to renew your domain
						names, even if you no longer use them.
						<li>Register Additional Domain Names </li>A typical method of fraud
						used by hackers is to register a domain name that is very close to
						your company name. At first glance, email addresses generated by
						bogus domain names may appear identical to your own. This could lead
						your contacts to believe they are emailing the genuine you. Consider
						registering domain names that are similar which could be utilized to
						deceive your contacts.
						<li>Set Up Email Authentication Measures</li>
						Setting up email authentication procedures on your domain may help
						to prevent email spoofing attacks if you have your own business
						domain that you use for emailing. A cyber-criminal could be able to
						send an email appearing to be from your email address without ever
						having to breach your email account. Email spoofing is analogous to
						faking the authorship of a letter. Anyone can write a return address
						on an envelope, but that doesn't mean it's from that location. Email
						spoofing occurs when someone forges an email's "From:" box to
						indicate that it was sent from a different email account than their
						own. Setting up email authentication procedures will identify emails
						that are not valid if someone attempts to spoof your email account.
						These methods assist to ensure that faked emails do not reach their
						intended recipient; instead, they are routed to the recipient's spam
						folder or are not delivered at all. Discuss adding Sender Policy
						Framework (SPF), DomainKeys Identified Mail (DKIM), and Domain-based
						Message Authentication, Reporting, and Conformance (DMARC) entries
						to your domain name with your service provider. If your DNS hosting
						is with a different provider, you will also need to contact them.
						For more information, you may head to ACSC's How to Combat Fake
						Emails page.
						<li> Protect Your Privacy </li>
						<li>Be cautious when uploading material that identifies: </li>
						What your job title is and where you work your company's email
						address your private email address Your email address may become a
						target for impersonation if it is available on several websites or
						forums. Visit the Office of the Australian Information Commissioner
						(OAIC) at oaic.gov.au for further information on how to manage your
						information online.
					</p>
				

					<h1>Quiz</h1>
					<quiz></quiz>
					<h1> Game</h1>
					</Text>
				</ContentWithPaddingXl>
			</Container>
			<Footer />
		</AnimationRevealPage>
	);
};
